### ISSUE TITLE
Cannot start on linux (ubuntu 16 - 64 bits)

### ISSUE THREAD

**Issue by userquin** [Panda-Programming-Language/Pandomium#4]
Hi:

The native loader (PandomiumNativeLoader) loads missing dynamic libraries for linux:

chrome_elf.so is missing: does not exist in pandomium-linux/native/linux64-native.tar.xz file also missing from https://pandomium.panda-lang.org/download/native/1.0.0/linux64-native.tar.xz

jcef.so is missing: only exists libjcef.so

Bye.

**Comment by dzikoysk** [comment]
I haven't tested the linux version yet, because I'm focued on windows. I've just packed the default output from jcef build. I'll build it again later (I think after I modify jcef source)

**Comment by userquin** [comment]
Let's go from bad to worse, this morning the windows computer only with the
intellij started and with the application of pandomium gives me the famous
blue screen of windows, there must be a serious problem with the native
part.

Now Intellij gets corrupted, I need to reinstall it.



2017-06-03 19:03 GMT+02:00 Dzikoysk <notifications@github.com>:

**Comment by userquin** [comment]
Upps, sorry bad ticket, this is related with windows 10 bug

2017-06-04 14:33 GMT+02:00 Joaquín Sánchez <userquin@gmail.com>:

**Comment by dzikoysk** [comment]
Fixed in 30ebb749110f16a8ce4a006e5d643f67a474453c & 427361c977917cd8adfc8e36a36283f54258f4c2
