### ISSUE TITLE
Question about universal.jar

### ISSUE THREAD

**Issue by userquin** [Panda-Programming-Language/Pandomium#5]
Hi:

With the latest change made including CefThreadBridge it is a little confusing the use of universal.jar: this jar includes all necessary dependencies in one single jar, but org.cef package is from original jcef.

If I build the project, I assume that I must use the jar from pandomium module including its libs/resources jars also including native ones for jogl.

Is that correct?

Bye.

**Comment by dzikoysk** [comment]
When you build a project, duplicated classes from dependencies are overwritten by those in the project, so it's not a problem. Ofc, I'll remove this package at the next native build.
