### ISSUE TITLE
How to hide this menu inspector source code.

### ISSUE THREAD

**Issue by burstbeta** [Panda-Programming-Language/Pandomium#6]
How to hide this inspector source code menu.

I don't want user to inspect my source code.

`
PandomiumSettings settings = PandomiumSettings.getDefaultSettings();
		
		
        Pandomium pandomium = new Pandomium(settings);
        pandomium.initialize();

        PandomiumClient client = pandomium.createClient();
        PandomiumBrowser browser = client.loadURL("https://www.google.co.th/");

        JFrame frame = new JFrame();
        frame.getContentPane().add(browser.toAWTComponent(), BorderLayout.CENTER);
        frame.pack();
        
        

        frame.setDefaultCloseOperation(WindowConstants.DO_NOTHING_ON_CLOSE);
        frame.addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosing(WindowEvent e) {
                pandomium.dispose();
                frame.dispose();
            }
        });

        frame.setTitle("Pandomium");
        frame.setSize(1380, 760);
        frame.setVisible(true);
`

![bug](https://user-images.githubusercontent.com/15885342/33113597-b0de6bfc-cf8b-11e7-86d6-14afabf42803.png)

**Comment by dzikoysk** [comment]
You can extract jcef object from wrappers - `getCefClient` for `PandomiumClient`. 
```
// [...]
PandomiumClient client = pandomium.createClient();
client.getCefClient().removeContextMenuHandler();
```

**Comment by burstbeta** [comment]
this `client.getCefClient().removeContextMenuHandler();` not working

but when implement custom context menu by CefContextMenuHandler . It work.

`
client.getCefClient().addContextMenuHandler(new CefContextMenuHandler(){
        	@Override
        	public void onBeforeContextMenu(CefBrowser arg0, CefContextMenuParams arg1, CefMenuModel arg2) {
        		// TODO Auto-generated method stub
        		arg2.clear();
        		System.out.println("onBeforeContextMenu : Clear");
        	}@Override
        	public boolean onContextMenuCommand(CefBrowser arg0, CefContextMenuParams arg1, int arg2, int arg3) {
        		// TODO Auto-generated method stub
        		
        		System.out.println("onBeforeContextMenu");
        		return false;
        	}@Override
        	public void onContextMenuDismissed(CefBrowser arg0) {
        		// TODO Auto-generated method stub
        		System.out.println("onBeforeContextMenu");
        	}
        });
`

Thank you @dzikoysk
